Repository Sseom/Smssme, pull requests merged in 2024-10, with the labels that each got.

#238 [hotfix] 1.3.3 버전 배포 중 비회원 로그인 시 마이페이지에서 앱 꺼지는 문제 발생
  Smssme/Notification/NotificationManager.swift
  Smssme/Scenes/Authentication/Login/Controller/LoginVC.swift
  Smssme/Scenes/Authentication/Mypage/Controller/MypageVC.swift
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/Controller/View/MainPageView.swift
Labels: 안지현

#253 [feal] 미래 예상 자산 차트
  Smssme.xcodeproj/project.pbxproj
  Smssme/Common/Chart/ChartDataManager.swift
  Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphCell.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphFirstView.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphSecondView.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphView.swift
Labels: 전성진

#257 247 rxfixmoneydiary
  Smssme.xcodeproj/project.pbxproj
  Smssme/Common/Extension/String+.swift
  Smssme/Common/Extension/UIViewController+Reactive.swift
  Smssme/Scenes/MoneyDiary/AutomaticTransactionView/View/AutomaticTransactionVC.swift
  Smssme/Scenes/MoneyDiary/AutomaticTransactionView/ViewModel/AutomaticTransactionVM.swift
  Smssme/Scenes/MoneyDiary/Creat_EditTransactionView/View/BenefitView.swift
  Smssme/Scenes/MoneyDiary/Creat_EditTransactionView/View/MoneyDiaryEditVC.swift
  Smssme/Scenes/MoneyDiary/Creat_EditTransactionView/ViewModel/MoneyDiaryCreationVM.swift
  Smssme/Scenes/MoneyDiary/DailyTransactionView/View/DailyTransactionVC.swift
  Smssme/Scenes/MoneyDiary/DailyTransactionView/View/DailyTransactionView.swift
  Smssme/Scenes/MoneyDiary/DailyTransactionView/ViewModel/DailyTransactionVM.swift
  Smssme/Scenes/MoneyDiary/MainView/View/MoneyDiaryVC.swift
  Smssme/Scenes/MoneyDiary/MainView/ViewModel/DiaryCalendarVM.swift
  Smssme/Scenes/MoneyDiary/MainView/ViewModel/MoneyDiaryVM.swift
Labels: 김리인

#259 알림 기능 추가 및 심사 거절 요소 해결
  Smssme/Notification/NotificationManager.swift
  Smssme/Scenes/Authentication/SignUp/View/EditUserInfoView.swift
  Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphFirstView.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphSecondView.swift
  Smssme/Scenes/Root/Controller/TabBarController.swift
Labels: 전성진, 안지현
