Repository Sseom/Smssme, pull requests merged in 2024-09, with the labels that each got.

#52 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 안지현

#53 Update .gitignore
  .gitignore
Labels: 안지현

#54 Feature/#8 sign up Splash 생성 및 로그인 상태에 따른 화면 전환 추가
  Smssme.xcodeproj/project.pbxproj
  Smssme/Assets.xcassets/splash.imageset/Contents.json
  Smssme/Assets.xcassets/splash.imageset/splash.png
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/Mypage/MypageViewController.swift
  Smssme/Controller/TabBarController.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Login/LoginView.swift
  Smssme/View/Login/SignUpView.swift
  Smssme/View/Login/SplashViewController.swift
  Smssme/View/Mypage/MypageView.swift
  Smssme/View/Util/CommonAlert.swift
  Smssme/View/Util/KeyboardEvader.swift
Labels: 안지현

#56 [commit]: Splash 임시 주석
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/TabBarController.swift
  Smssme/Firebase/GoogleService-Info.plist
  Smssme/SceneDelegate.swift
Labels: 안지현

#63 [feat] 선택창 타이틀 설명 반영, 화면 흐름 정렬 #62
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/View/FinancialPlan/FinancialPlanCell.swift
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/Util/UIComponentFactory.swift
Labels: 임혜정

#69 Feature/#8 sign up
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/Mypage/MypageViewController.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Firebase/FirebaseAuthenticationManager.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Mypage/EditUserInfo.swift
  Smssme/View/Mypage/MypageView.swift
Labels: 안지현

#73 [feat] 자산플랜_모델 생성, 플랜생성 및 수정창 유효성검사기능 #64
  Smssme/AppDelegate.swift
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanEditPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Model/CoreData/Goal/Goal+CoreDataClass.swift
  Smssme/Model/CoreData/Goal/Goal+CoreDataProperties.swift
  Smssme/Model/CoreData/Goal/GoalCoreDataManager.swift
  Smssme/Model/CoreData/User/User+CoreDataProperties.swift
  Smssme/SceneDelegate.swift
  Smssme/View/FinancialPlan/FinancialPlanCell.swift
  Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
  Smssme/View/FinancialPlan/PlanCustomTextField.swift
Labels: 임혜정

#81 Feature/#6 main page view
  Smssme/Controller/Assets/AssetsEditVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Model/CoreData/Assets/Assets+CoreDataProperties.swift
  Smssme/Model/CoreData/Assets/AssetsCoreDataManager.swift
  Smssme/Model/DateModel.swift
  Smssme/View/Assets/AssetsEditView.swift
  Smssme/View/MainPage/MainPageView.swift
Labels: 전성진

#82 [feat] 자산플랜 선택창_커스텀플랜UI 수정, 자산플랜_입력값 로직 #75
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Model/CoreData/Goal/FinancialPlanManager.swift
  Smssme/Model/CoreData/Goal/Goal+CoreDataProperties.swift
  Smssme/Model/CoreData/Goal/GoalCoreDataManager.swift
  Smssme/SceneDelegate.swift
  Smssme/View/FinancialPlan/FinancialPlanCell.swift
  Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
  Smssme/View/FinancialPlan/FinancialPlanSelectView.swift
  Smssme/View/FinancialPlan/PlanCustomTextField.swift
Labels: 임혜정

#88 마이페이지 UI 작업 수정
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/Mypage/TestTableViewCell.swift
  Smssme/Controller/Mypage/TestTableViewController.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Mypage/MypageView.swift
  Smssme/View/Mypage/MypageViewCell.swift
Labels: 안지현

#100 마이페이지 관련 버그 수정
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/Mypage/TestTableViewCell.swift
  Smssme/Controller/Mypage/TestTableViewController.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Firebase/FirebaseAuthenticationManager.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Model/UserProfile.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Login/SignUpView.swift
  Smssme/View/Mypage/MypageView.swift
Labels: 안지현

#113 #105/feat/collaboration branch 수입/지출에 따른 총 금액 색상 변경
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/MoneyDiary/DailyTransaction/DailyTransactionVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryCreatVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryEditVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Model/CoreData/Diary/Goal/FinancialPlanManager.swift
  Smssme/Model/CoreData/Diary/Goal/Goal+CoreDataClass.swift
  Smssme/Model/CoreData/Diary/Goal/Goal+CoreDataProperties.swift
  Smssme/Model/CoreData/Diary/Goal/GoalCoreDataManager.swift
  Smssme/Model/DateModel.swift
  Smssme/SceneDelegate.swift
  Smssme/View/MoneyDiary/DailyTransaction/DailyTransactionCell.swift
  Smssme/View/MoneyDiary/DailyTransaction/DailyTransactionView.swift
  Smssme/View/MoneyDiary/MoneyDiaryCalendarCell.swift
  Smssme/View/MoneyDiary/MoneyDiaryCreateView.swift
  Smssme/View/MoneyDiary/MoneyDiaryView.swift
  Smssme/View/Mypage/EditUserInfo.swift
Labels: 안지현

#121 Feature/#97 mypage detail
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Controller/TabBarController.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Login/LoginView.swift
  Smssme/View/Login/SignUpView.swift
  Smssme/View/MainPage/MainPageView.swift
  Smssme/View/Util/UIComponentFactory.swift
Labels: 안지현

#123 Feature/#35 money diary edit UI
  Smssme/Controller/MoneyDiary/MoneyDiaryBudgetEditVC.swift
  Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
  Smssme/Model/DateModel.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditCell.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditHeaderView.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditView.swift
  Smssme/View/MoneyDiary/MoneyDiaryView.swift
  Smssme/View/Util/DateManager.swift
Labels: 전성진

#125 [ref] 예산안 VC 초기화 버그 수정
  Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
Labels: 전성진

#126 [feat]: 생년월일 피커뷰로 수정/ 메인페이지 로그인 유무에 따른 welcomeTitle 변경
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/View/Login/LoginView.swift
  Smssme/View/Login/SignUpView.swift
  Smssme/View/MainPage/MainPageView.swift
Labels: 안지현

#129 Feature/#97 mypage detail
  Smssme/Assets.xcassets/logo.imageset/Contents.json
  Smssme/Assets.xcassets/logo.imageset/logo.png
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/View/Login/SignUpView.swift
Labels: 안지현

#133 [ref]: 주석 처리된 부분 전체적으로 삭제
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Assets/AssetsEditVC.swift
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryCreatVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryEditVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Firebase/FirebaseAuthenticationManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/Model/UserProfile.swift
  Smssme/View/Assets/AssetsEditView.swift
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/Login/LoginView.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditCell.swift
  Smssme/View/MoneyDiary/MoneyDiaryEditView.swift
  Smssme/View/Util/KeyboardEvader.swift
Labels: 안지현

#148 Feature/#35 money diary edit UI
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryBudgetEditVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/SignUp/AgreementVC.swift
  Smssme/Controller/SignUp/AgreementView.swift
  Smssme/Controller/SignUp/EmailVC.swift
  Smssme/Controller/SignUp/EmailView.swift
  Smssme/Controller/SignUp/IncomeAndLocationVC.swift
  Smssme/Controller/SignUp/IncomeAndLocationView.swift
  Smssme/Controller/SignUp/NickNameVC.swift
  Smssme/Controller/SignUp/NickNameView.swift
  Smssme/Controller/SignUp/PasswordVC.swift
  Smssme/Controller/SignUp/PasswordView.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/Model/DateModel.swift
  Smssme/Model/UserProfileModel.swift
  Smssme/View/Login/LoginView.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditHeaderView.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditView.swift
  Smssme/View/MoneyDiary/MoneyDiaryView.swift
  Smssme/View/SignUp/SignUpView.swift
  Smssme/View/Util/UITextField.swift
Labels: 전성진

#151 [feat]: 회원가입 UI 수정 완료 및 파이어베이스 연결
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/SignUp/AgreementView.swift
  Smssme/Controller/SignUp/EmailVC.swift
  Smssme/Controller/SignUp/EmailView.swift
  Smssme/Controller/SignUp/IncomeAndLocationVC.swift
  Smssme/Controller/SignUp/IncomeAndLocationView.swift
  Smssme/Controller/SignUp/NickNameVC.swift
  Smssme/Controller/SignUp/PasswordVC.swift
  Smssme/Controller/SignUp/PasswordView.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/Model/UserProfileModel.swift
  Smssme/View/Util/ToastMessage.swift
Labels: 안지현

#154 hotfix/#153 은퇴자금 이미지 안나오는거
  Smssme/Assets.xcassets/FinancialPlan/carConfirm.imageset/carConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/confirmWedding.imageset/Contents.json
  Smssme/Assets.xcassets/FinancialPlan/confirmWedding.imageset/confirmWedding.png
  Smssme/Assets.xcassets/FinancialPlan/houseConfirm.imageset/houseConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/myPlanConfirm.imageset/myPlanConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/retirementConfirm.imageset/Contents.json
  Smssme/Assets.xcassets/FinancialPlan/retirementConfirm.imageset/retirementConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/seniorConfirm.imageset/seniorConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/travelConfirm.imageset/travelConfirm.png
  Smssme/Assets.xcassets/FinancialPlan/weddingConfirm.imageset/weddingConfirm.png
  Smssme/Assets.xcassets/dummy.imageset/AdobeStock_627676653.jpg
  Smssme/Assets.xcassets/dummy.imageset/Contents.json
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/FinancialPlan/FinancialPlanCurrentPlanCell.swift
Labels: 임혜정

#156 [Feat] 자산 목록 뷰 추가
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Assets/AssetsListVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryBudgetEditVC.swift
  Smssme/Model/DateModel.swift
  Smssme/View/Assets/AssetsListCell.swift
  Smssme/View/Assets/AssetsListHeaderView.swift
  Smssme/View/Assets/AssetsListView.swift
  Smssme/View/MoneyDiary/MoneyDiaryBudgetEditView.swift
Labels: 전성진

#171 회원가입
  .gitignore
  SecretsConfig.xcconfig
  Smssme.xcodeproj/project.pbxproj
  Smssme/AppDelegate.swift
  Smssme/Assets.xcassets/kakao_login.imageset/Contents.json
  Smssme/Assets.xcassets/kakao_login.imageset/kakao_login.png
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/Mypage/MypageVC.swift
  Smssme/Controller/SignUp/EmailVC.swift
  Smssme/Controller/SignUp/EmailView.swift
  Smssme/Controller/SignUp/IncomeAndLocationVC.swift
  Smssme/Controller/SignUp/IncomeAndLocationView.swift
  Smssme/Controller/SignUp/NickNameVC.swift
  Smssme/Controller/SignUp/NickNameView.swift
  Smssme/Controller/SignUp/PasswordVC.swift
  Smssme/Controller/SignUp/PasswordView.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/Info.plist
  Smssme/Model/APIModel.swift
  Smssme/Model/UserProfileModel.swift
  Smssme/Network/Endpoint.swift
  Smssme/Network/NetworkManager.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Login/LoginView.swift
Labels: 안지현

#175 Feat/#167 재무목표플랜_매월 저축금액, 첫 회원 초기화면설정 etc
  .gitignore
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanEditPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryBudgetEditVC.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryCreatVC.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
  Smssme/Model/CoreData/FinancialPlan/FinancialPlan.swift
  Smssme/Model/CoreData/FinancialPlan/FinancialPlanManager.swift
  Smssme/Model/CoreData/FinancialPlan/FinancialPlanService.swift
  Smssme/Smssme.xcdatamodeld/Smssme.xcdatamodel/contents
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/MoneyDiary/MoneyDiaryCreateView.swift
Labels: 임혜정

#180 Fix/#174 플랜 타이틀 수정기능, 카테고리 당 1개 제한 해제
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreationVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanEditPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Model/CoreData/FinancialPlan/FinancialPlan.swift
  Smssme/Model/CoreData/FinancialPlan/FinancialPlanService.swift
  Smssme/View/FinancialPlan/FinancialPlanCreationView.swift
  Smssme/View/FinancialPlan/FinancialPlanCurrentPlanView.swift
  Smssme/View/FinancialPlan/FinancialPlanSelectionView.swift
Labels: 임혜정

#187 dev로 합치기 위한 pr
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/Authentication/Login/LoginVC.swift
  Smssme/Controller/Authentication/Login/ReauthenticationVC.swift
  Smssme/Controller/Authentication/Mypage/MypageVC.swift
  Smssme/Controller/Authentication/Mypage/ResetPasswordVC.swift
  Smssme/Controller/Authentication/SignUp/EmailVC.swift
  Smssme/Controller/Authentication/SignUp/IncomeAndLocationVC.swift
  Smssme/Controller/Authentication/SignUp/NickNameVC.swift
  Smssme/Controller/Authentication/SignUp/PasswordVC.swift
  Smssme/Controller/Authentication/SignUp/SignUpVC.swift
  Smssme/Controller/MainPage/MainPageVC.swift
  Smssme/Controller/SignUp/AgreementVC.swift
  Smssme/Controller/SignUp/AgreementView.swift
  Smssme/Controller/SplashViewController.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Authentication/Login/LoginView.swift
  Smssme/View/Authentication/Login/ReauthenticationView.swift
  Smssme/View/Authentication/Mypage/MypageView.swift
  Smssme/View/Authentication/Mypage/MypageViewCell.swift
  Smssme/View/Authentication/Mypage/ResetPasswordView.swift
  Smssme/View/Authentication/SignUp/EmailView.swift
  Smssme/View/Authentication/SignUp/IncomeAndLocationView.swift
  Smssme/View/Authentication/SignUp/NickNameView.swift
  Smssme/View/Authentication/SignUp/PasswordView.swift
  Smssme/View/Authentication/SignUp/SignUpView.swift
  Smssme/View/Mypage/MypageView.swift
  Smssme/View/Util/CommonAlert.swift
Labels: 안지현

#197 etc/깃이그노어 파일 추가 작업
  .gitignore
  Smssme.xcodeproj/project.pbxproj
  Smssme/AppDelegate.swift
  Smssme/GoogleService-Info.plist
  Smssme/Info.plist
  Smssme/Model/CoreData/Budget/Budget+CoreDataProperties.swift
  Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
  Smssme/Network/DataModel/APIModel.swift
  Smssme/Network/NetworkManager.swift
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/View/MainPageView.swift
Labels: 안지현

#198 etc/UI디자인 시스템 _레이블만, 수정페이지 타이틀 저장
  .gitignore
  Smssme.xcodeproj/project.pbxproj
  Smssme/Common/UI/UIComponentFactory.swift
  Smssme/Common/UI/UILabelFactory.swift
  Smssme/Scenes/FinancialPlan/Controller/FinancialPlanEditPlanVC.swift
  Smssme/Scenes/FinancialPlan/View/FinancialPlanCell.swift
  Smssme/Scenes/FinancialPlan/View/FinancialPlanConfirmView.swift
  Smssme/Scenes/FinancialPlan/View/FinancialPlanCreationView.swift
  Smssme/Scenes/FinancialPlan/View/FinancialPlanCurrentPlanView.swift
  Smssme/Scenes/FinancialPlan/View/FinancialPlanSelectionView.swift
Labels: 임혜정

#200 [fix] 지출 내역 편집 버그 수정
  Smssme/Scenes/Assets/Controller/AssetsListVC.swift
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/View/MainPageView.swift
  Smssme/Scenes/MoneyDiary/Controller/MoneyDiaryBudgetEditVC.swift
  Smssme/Scenes/MoneyDiary/Controller/MoneyDiaryEditVC.swift
  Smssme/Scenes/MoneyDiary/View/MoneyDiaryEditView.swift
Labels: 전성진

#202 MainPage - 주요경제지수 API 연결 및 청년혜택 테이블뷰 UI 개선
  Smssme.xcodeproj/project.pbxproj
  Smssme/Assets.xcassets/Benefits/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit1.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit1.imageset/benefit4.png
  Smssme/Assets.xcassets/Benefits/benefit2.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit2.imageset/benefit2.png
  Smssme/Assets.xcassets/Benefits/benefit3.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit3.imageset/benefit3.png
  Smssme/Assets.xcassets/Benefits/benefit4.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit4.imageset/benefit5.png
  Smssme/Assets.xcassets/Benefits/benefit5.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit5.imageset/benefit1.png
  Smssme/Assets.xcassets/Benefits/benefit6.imageset/Contents.json
  Smssme/Assets.xcassets/Benefits/benefit6.imageset/benefit6.png
  Smssme/Network/DataModel/APIModel.swift
  Smssme/Scenes/Authentication/Mypage/Controller/MypageVC.swift
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/View/BenefitVerticalCell.swift
  Smssme/Scenes/MainPage/View/MainPageView.swift
  Smssme/Scenes/MainPage/View/StockIndexCell.swift
Labels: 안지현

#214 [feat] 미래 예상 자산 그래프
  Smssme.xcodeproj/project.pbxproj
  Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphCell.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphView.swift
Labels: 전성진

#215 Ref/#204 firebase
  Smssme.xcodeproj/project.pbxproj
  Smssme/Common/Formatter/RegexManager.swift
  Smssme/Common/KeyboardEvader.swift
  Smssme/Common/UI/ToastMessage.swift
  Smssme/Common/UI/UILabelFactory.swift
  Smssme/Firebase/FirebaseFirestoreManager.swift
  Smssme/Firebase/FirebaseManager.swift
  Smssme/Network/DataModel/APIModel.swift
  Smssme/Network/Endpoint.swift
  Smssme/Network/NetworkManager.swift
  Smssme/Scenes/Authentication/Login/Controller/LoginVC.swift
  Smssme/Scenes/Authentication/Login/View/LoginView.swift
  Smssme/Scenes/Authentication/Mypage/Controller/MypageVC.swift
  Smssme/Scenes/Authentication/Mypage/Controller/ResetPasswordVC.swift
  Smssme/Scenes/Authentication/Mypage/View/MypageViewCell.swift
  Smssme/Scenes/Authentication/SignUp/Controller/EditUserInfo.swift
  Smssme/Scenes/Authentication/SignUp/Controller/EmailVC.swift
  Smssme/Scenes/Authentication/SignUp/View/EmailView.swift
  Smssme/Scenes/Authentication/SignUp/View/SignUpView.swift
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/View/BenefitVerticalCell.swift
  Smssme/Scenes/MainPage/View/MainPageView.swift
  Smssme/Scenes/MainPage/View/StockIndexCell.swift
  Smssme/Scenes/Root/Controller/SplashViewController.swift
  Smssme/Scenes/Root/Controller/TabBarController.swift
Labels: 안지현

#217 [feat] 미래 예상 자산 그래프 데이터 표출 방식 수정, 그래프 애니메이션 적용, 자산 편집 뷰 디자인 수정
  Smssme/Scenes/Assets/View/AssetsEditView.swift
  Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
  Smssme/Scenes/FutureGraph/View/FutureGraphView.swift
  Smssme/Scenes/MoneyDiary/Controller/MoneyDiaryBudgetEditVC.swift
Labels: 전성진

#218 [fix] 메인 페이지 차트 문구 변경
  Smssme/Scenes/MainPage/Controller/MainPageVC.swift
  Smssme/Scenes/MainPage/View/MainPageView.swift
Labels: 전성진

#221 etc/깃이그노어에 추가한 xcconig 및 plist 파일이 추적되는 문제
  .gitignore
  Smssme.xcodeproj/project.pbxproj
Labels: 안지현
