Repository Sseom/Smssme, pull requests merged in 2024-08, with the labels that each got.

#2 1 feat/ #1 UIComponent - LabelFactory
  Smssme.xcodeproj/project.pbxproj
  Smssme/SceneDelegate.swift
  Smssme/View/UIComponentFactory.swift
Labels: 임혜정

#16 하단 네번째 탭바에 로그인 뷰 임시 추가
  Smssme.xcodeproj/project.pbxproj
  Smssme/Common/Model.swift
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/TabBarController.swift
  Smssme/SceneDelegate.swift
  Smssme/View/Login/LoginView.swift
Labels: 안지현

#18 [feat] 자산플랜 - 목표작성 페이지 UI 완료, 텍스트필드 생성기
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Controller/FinancialPlanCreateVC.swift
  Smssme/Controller/TabBarController.swift
  Smssme/View/FinancialPlan/FinancialPlanCell.swift
  Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
  Smssme/View/FinancialPlan/FinancialPlanSelectView.swift
  Smssme/View/FinancialPlan/PlanCustomTextField.swift
  Smssme/View/FinancialPlanCreateView.swift
  Smssme/View/UIComponentFactory.swift
Labels: 임혜정

#24 [feat] 자산플랜 결과확인창UI, 헥사코드
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
  Smssme/View/UIColorSet.swift
Labels: 임혜정

#25 #5 Feat: 켈린더 제작
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/MoneyDiary/MoneyDiaryCalendarCell.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryCalendarView.swift
  Smssme/Controller/MoneyDiary/MoneyDiaryView.swift
  Smssme/Controller/TabBarController.swift
  Smssme/Controller/ViewController.swift
  Smssme/Model/DateModel.swift
  Smssme/Model/Model.swift
  Smssme/View/MoneyDiary/MoneyDiaryVC.swift
Labels: 김리인

#29 Feature/#8 sign up 파이어베이스 회원가입 연동
  Smssme.xcodeproj/project.pbxproj
  Smssme.xcodeproj/xcshareddata/xcschemes/Smssme.xcscheme
  Smssme/AppDelegate.swift
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Firebase/GoogleService-Info.plist
  Smssme/GoogleService-Info.plist
  Smssme/View/Login/LoginView.swift
  Smssme/View/Login/SignUpView.swift
  Smssme/View/UIComponentFactory.swift
Labels: 안지현

#45 [etc] CoreData Entity, DataManager 추가
  Smssme.xcodeproj/project.pbxproj
  Smssme/Model/CoreData/Assets/Assets+CoreDataClass.swift
  Smssme/Model/CoreData/Assets/Assets+CoreDataProperties.swift
  Smssme/Model/CoreData/Assets/AssetsCoreDataManager.swift
  Smssme/Model/CoreData/Budget/Budget+CoreDataClass.swift
  Smssme/Model/CoreData/Budget/Budget+CoreDataProperties.swift
  Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
  Smssme/Model/CoreData/Diary/Diary+CoreDataClass.swift
  Smssme/Model/CoreData/Diary/Diary+CoreDataProperties.swift
  Smssme/Model/CoreData/Diary/DiaryCoreDataManager.swift
  Smssme/Model/CoreData/Goal/Goal+CoreDataClass.swift
  Smssme/Model/CoreData/Goal/Goal+CoreDataProperties.swift
  Smssme/Model/CoreData/Goal/GoalCoreDataManager.swift
  Smssme/Model/CoreData/User/User+CoreDataClass.swift
  Smssme/Model/CoreData/User/User+CoreDataProperties.swift
  Smssme/Model/CoreData/User/UserCoreDataManager.swift
  Smssme/Smssme.xcdatamodeld/Smssme.xcdatamodel/contents
Labels: 전성진

#47 [feat] 자금플랜 진행중인 플랜페이지 UI
  Smssme.xcodeproj/project.pbxproj
  Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
  Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
  Smssme/Controller/Login/LoginVC.swift
  Smssme/Controller/Login/SignUpVC.swift
  Smssme/Controller/TabBarController.swift
  Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
  Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
  Smssme/View/FinancialPlan/FinancialPlanCurrentPlanView.swift
  Smssme/View/Util/UIComponentFactory.swift
Labels: 임혜정
